#!/bin/bash
set -e
script=${1}
option=${2}

if [ $script == "setup" ] ; then
  yarn && cd api && yarn && cd ../app && yarn

elif [ $script == "start-db" ] ; then
  docker-compose -f ./api/docker-compose.yml up

elif [ $script == "stop-db" ] ; then
  docker-compose -f ./api/docker-compose.yml down

elif [ $script == "start-api" ] ; then
  cd api && yarn dev

elif [ $script == "start-app" ] ; then
  cd app && yarn start

elif [ $script == "deploy" ] ; then
  now --public
  now alias

fi