version: '3'

services:

  packt-neo4js:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - './.data:/data'
    environment:
      - NEO4J_AUTH=neo4j/changeme